#!/bin/bash
#/ Usage: script/bootstrap
#/ Installs one-time dependencies.
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

if ! type rustup >/dev/null 2>&1; then
    fatal "rustup not found, please install it from https://rustup.rs/"
fi

if ! properly_configured; then
    fatal "No configuration found, run 'script/configure' first"
fi

rustup update

cargo install cargo-binutils
