#!/bin/bash
#/ Usage: script/qemu
#/ Launch the kernel in QEMU
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

# Read config
source script/helpers/load_config.sh

docker run -it --rm -v "$root_dir:/work" -w /work rustembedded/osdev-utils:2021.12 \
    $QEMU_CMD \
    $QEMU_MACHINE_ARGS \
    -display none -serial stdio \
    -kernel target/img/kernel-$arch-$board.img